# Check `ares-sc2/src/ares/config.yml` for valid config options
# Use this to override those values
# Can add own unique config options here if desired

# Custom values not used by ares
MyBotName: PiG_Bot
BotDebug: False  # Enable debug output for bot-specific systems (targeting, nova, etc.)
MyBotRace: Protoss
# setting ture allows auto upload to aiareana (https://aiarena.net/) on push to `main` branch
# see tutorial on readme before setting to True
AutoUploadToAiarena: True
########################
# Wall Generation Mode - when True, runs WallGeneratorBot instead of Main Bot
WallGenerationMode: False
########################

UseData: True
Debug: False

Distances:
    GroundEnemyNearBases: 25.
    GroundEnemyLeavingBases: 30.
GameStep: 4
DebugGameStep: 4

# Turn ares features on/off for performance reasons
Features:
    # this grid is useful for disruptor balls and maybe some other uses
    # off by default to save computation
    TacticalGroundGrid: True

DebugOptions:
    # one of: Air, AirVsGround, Ground, GroundAvoidance, AirAvoidance
    ActiveGrid: TacticalGround
    ChatDebug: True
    DebugSpawn: True
    ShowPathingCost: False
    ResourceDebug: False
    ShowBuildingFormation: False